import {ReactElement} from "react";
import styles from "./page.module.css"
import {Roboto} from "next/font/google";

const roboto = Roboto({weight: "300", subsets: ['latin']})

export default function Home(): ReactElement {
    return <div>
        <main className={styles.main}>
            <h1 className={roboto.className}>AI SOFTWARE TEST GUESSER</h1>
            <section>
                <h2>How it works</h2>
                <p>
                    You will receive three different versions of the same unit test case. One is written by a&nbsp;
                    <a href={"https://en.wikipedia.org/wiki/Human"}>human</a>, another is heavily assisted by&nbsp;
                    <a href={"https://github.com/features/copilot"}>GitHub Copilot</a>, and the third is entirely
                    generated by another <a href={"https://www.welltested.ai/"}>AI</a>, with minimal adjustments to
                    ensure functionality.
                </p>
                <p>
                    <b>
                        Your task is to guess which version is created by whom and provide an overall rating for each.
                    </b>&nbsp;
                    Additionally, you are encouraged to share your thoughts after evaluating each test case.
                </p>
            </section>
            <section>
                <p>
                    Your responses will be gathered anonymously for a small university study assessing the current state
                    of AI-written tests. As a reward, you will have the opportunity to see how your assessments compare
                    to those of others at the end.
                </p>
            </section>

            <a href="/quiz" className={styles.startLink}>Sounds good, let&apos;s start</a>
        </main>
    </div>;
}
