import {ReactElement} from "react";
import styles from "./page.module.css"
import {Roboto} from "next/font/google";
import Link from "next/link";

const roboto = Roboto({weight: "300", subsets: ['latin']})

export default function Home(): ReactElement {
    return <div>
        <main className={styles.main}>
            <header>
                <h1 className={roboto.className}>AI SOFTWARE TEST GUESSER</h1>
                <h2 className={roboto.className}>Can you tell which software test is written by AI?</h2>
            </header>
            <section>
                <h3>How does it work?</h3>
                <ol>
                    <li>
                        You will see a code snippet along with a short description as a reference.
                    </li>
                    <li>
                        Once you get a rough idea, close the reference to reveal the tests written for it. It is
                        possible to reopen the reference at any time. Understanding it completely is not necessary.
                    </li>
                    <li>
                        The test cases are either written by a&nbsp;
                        <a href={"https://en.wikipedia.org/wiki/Human"}>human</a>, heavily assisted by the AI tool&nbsp;
                        <a href={"https://github.com/features/copilot"}>GitHub Copilot</a>, or entirely generated by
                        another <a href={"https://www.welltested.ai/"}>AI</a>.
                    </li>
                    <li>
                        Your task is to <u>guess which version was created by which tool and rate each test.</u>
                        &nbsp;If you have any additional thoughts, feel free to add them just below the test code
                        snippets.
                    </li>
                </ol>
            </section>
            <section>
                <h3>What&apos;s in it for you?</h3>
                <p>
                    Upon completion, see <u>your results and how you compare with others.</u> The link to them is
                    permanent, so share them if you would like to :)
                </p>
            </section>
            <section>
                <h3>How long will this take?</h3>
                <p>
                    <u>Approximately 10 to 15 minutes.</u> You can take a break at any time; just keep the browser tab
                    open. There is no time limit.
                </p>
            </section>
            <section>
                <h3>Is any prior knowledge required?</h3>
                <p>
                    <u>If you can read code, you are good to go.</u> While prior&nbsp;
                    <a href={"https://flutter.dev/"}>Flutter</a> or <a href={"https://dart.dev/"}>Dart</a> experience
                    may be helpful, it is not necessary, as it is similar to other programming languages like Kotlin and
                    JavaScript, for example.
                </p>
            </section>
            <section>
                <p>
                    Your responses will be gathered anonymously for a small university study assessing the current state
                    of AI-written tests. Thank you for contribution.
                </p>
            </section>

            <Link href={"/quiz"} className={styles.startLink}>Sounds good, let&apos;s start</Link>
        </main>
    </div>;
}
