import {ReactElement} from "react";
import styles from "./page.module.css"
import {Roboto} from "next/font/google";
import Link from "next/link";

const roboto = Roboto({weight: "300", subsets: ['latin']})

export default function Home(): ReactElement {
    return <div>
        <main className={styles.main}>
            <h1 className={roboto.className}>AI SOFTWARE TEST GUESSER</h1>
            <section>
                <h2>How it works</h2>
                <p>
                    Before seeing any test code, the code to which the test applies will be shown to you, along with a
                    short description of the test case as a reference.
                </p>
                <p>
                    Once you close the reference, three different implementations of the test case described in the
                    reference are shown. One is written by a <a href={"https://en.wikipedia.org/wiki/Human"}>human</a>,
                    another is heavily assisted by <a href={"https://github.com/features/copilot"}>GitHub Copilot</a>,
                    and the third is entirely generated by another <a href={"https://www.welltested.ai/"}>AI</a>, with
                    minimal adjustments to ensure functionality.
                </p>
                <p>
                    <b>
                        Your task is to guess which version was created by whom and provide an overall rating for each.
                    </b>&nbsp;
                    Additionally, you are encouraged to share your thoughts after evaluating each test case.
                </p>
            </section>
            <section>
                <p>
                    Your responses will be gathered anonymously for a small university study assessing the current state
                    of AI-written tests. As a reward, you will see how your assessments compare to those of others at
                    the end.
                </p>
            </section>

            <Link href={"/quiz"} className={styles.startLink}>Sounds good, let&apos;s start</Link>
        </main>
    </div>;
}
